//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rise.Client.Resources.Pages.Resto {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resto() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rise.Client.Resources.Pages.Resto.Resto", typeof(Resto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergenen? Vraag meer info bij de medewerkers.
        /// </summary>
        internal static string AllergensInfo {
            get {
                return ResourceManager.GetString("AllergensInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Kies een campus --.
        /// </summary>
        internal static string ChooseCampus {
            get {
                return ResourceManager.GetString("ChooseCampus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen menu voor {0}..
        /// </summary>
        internal static string NoMenuFor {
            get {
                return ResourceManager.GetString("NoMenuFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen menu gevonden voor dit restaurant..
        /// </summary>
        internal static string NoMenuFound {
            get {
                return ResourceManager.GetString("NoMenuFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        internal static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resto weekmenu.
        /// </summary>
        internal static string RestoWeekmenu {
            get {
                return ResourceManager.GetString("RestoWeekmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Selecteer een restaurant --.
        /// </summary>
        internal static string SelectRestaurant {
            get {
                return ResourceManager.GetString("SelectRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vegan &amp; halal.
        /// </summary>
        internal static string VeganHalal {
            get {
                return ResourceManager.GetString("VeganHalal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to veggie &amp; halal.
        /// </summary>
        internal static string VeggieHalal {
            get {
                return ResourceManager.GetString("VeggieHalal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week van.
        /// </summary>
        internal static string WeekOf {
            get {
                return ResourceManager.GetString("WeekOf", resourceCulture);
            }
        }
    }
}
