//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rise.Client.Resources.MainComponents.Filtering {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Filter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Filter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rise.Client.Resources.MainComponents.Filtering.Filter", typeof(Filter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle.
        /// </summary>
        internal static string Alle {
            get {
                return ResourceManager.GetString("Alle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles.
        /// </summary>
        internal static string Alles {
            get {
                return ResourceManager.GetString("Alles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andere.
        /// </summary>
        internal static string Andere {
            get {
                return ResourceManager.GetString("Andere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultuur.
        /// </summary>
        internal static string Cultuur {
            get {
                return ResourceManager.GetString("Cultuur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eten.
        /// </summary>
        internal static string Eten {
            get {
                return ResourceManager.GetString("Eten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelezen.
        /// </summary>
        internal static string Gelezen {
            get {
                return ResourceManager.GetString("Gelezen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratis.
        /// </summary>
        internal static string Gratis {
            get {
                return ResourceManager.GetString("Gratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kledij.
        /// </summary>
        internal static string Kledij {
            get {
                return ResourceManager.GetString("Kledij", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onderwijs.
        /// </summary>
        internal static string Onderwijs {
            get {
                return ResourceManager.GetString("Onderwijs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongelezen.
        /// </summary>
        internal static string Ongelezen {
            get {
                return ResourceManager.GetString("Ongelezen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        internal static string Sport {
            get {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        internal static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentenjob.
        /// </summary>
        internal static string Studentenjob {
            get {
                return ResourceManager.GetString("Studentenjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentenvereniging.
        /// </summary>
        internal static string Studentenvereniging {
            get {
                return ResourceManager.GetString("Studentenvereniging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech.
        /// </summary>
        internal static string Tech {
            get {
                return ResourceManager.GetString("Tech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuis.
        /// </summary>
        internal static string Thuis {
            get {
                return ResourceManager.GetString("Thuis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vast.
        /// </summary>
        internal static string Vast {
            get {
                return ResourceManager.GetString("Vast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welzijn.
        /// </summary>
        internal static string Welzijn {
            get {
                return ResourceManager.GetString("Welzijn", resourceCulture);
            }
        }
    }
}
