//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rise.Client.Resources.Pages.Notifications {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rise.Client.Resources.Pages.Notifications.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles.
        /// </summary>
        public static string Alles {
            get {
                return ResourceManager.GetString("Alles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle notificaties zijn gelezen.
        /// </summary>
        public static string AllRead {
            get {
                return ResourceManager.GetString("AllRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, notificatie kon niet verwijderd worden.
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen notificaties gevonden.
        /// </summary>
        public static string EmptyNotifications {
            get {
                return ResourceManager.GetString("EmptyNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je moet ingelogd zijn om notificaties te raadplegen.
        /// </summary>
        public static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De notificatie kon niet als gelezen worden ingesteld. Probeer het later opnieuw..
        /// </summary>
        public static string MarkAsReadError {
            get {
                return ResourceManager.GetString("MarkAsReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U heeft een nieuwe notificatie.
        /// </summary>
        public static string NewNotification {
            get {
                return ResourceManager.GetString("NewNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificatie is verwijderd..
        /// </summary>
        public static string NotificationDeleted {
            get {
                return ResourceManager.GetString("NotificationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificatie wordt geladen....
        /// </summary>
        public static string NotificationLoading {
            get {
                return ResourceManager.GetString("NotificationLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelezen.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoek notificaties....
        /// </summary>
        public static string SearchNotification {
            get {
                return ResourceManager.GetString("SearchNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaties.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaties.
        /// </summary>
        public static string TitleNotifications {
            get {
                return ResourceManager.GetString("TitleNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongelezen.
        /// </summary>
        public static string Unread {
            get {
                return ResourceManager.GetString("Unread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ongelezen berichten.
        /// </summary>
        public static string unreadMessages {
            get {
                return ResourceManager.GetString("unreadMessages", resourceCulture);
            }
        }
    }
}
