//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rise.Client.Resources.Pages.CampusLife {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CampusLife {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CampusLife() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rise.Client.Resources.Pages.CampusLife.CampusLife", typeof(CampusLife).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kortingscode gekopieerd naar klembord!.
        /// </summary>
        internal static string CodeCopied {
            get {
                return ResourceManager.GetString("CodeCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopieer link.
        /// </summary>
        internal static string CopyLink {
            get {
                return ResourceManager.GetString("CopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal wordt geladen....
        /// </summary>
        internal static string DealLoading {
            get {
                return ResourceManager.GetString("DealLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim kortingscode.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eten.
        /// </summary>
        internal static string Eten {
            get {
                return ResourceManager.GetString("Eten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job wordt geladen....
        /// </summary>
        internal static string JobLoading {
            get {
                return ResourceManager.GetString("JobLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link gekopieerd naar klembord!.
        /// </summary>
        internal static string LinkCopied {
            get {
                return ResourceManager.GetString("LinkCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuur een e-mail.
        /// </summary>
        internal static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er werden geen verenigingen gevonden..
        /// </summary>
        internal static string NoClubsFound {
            get {
                return ResourceManager.GetString("NoClubsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er werden geen deals gevonden..
        /// </summary>
        internal static string NoDealsFound {
            get {
                return ResourceManager.GetString("NoDealsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er werden geen jobs gevonden..
        /// </summary>
        internal static string NoJobsFound {
            get {
                return ResourceManager.GetString("NoJobsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oeps!.
        /// </summary>
        internal static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lees minder.
        /// </summary>
        internal static string ReadLess {
            get {
                return ResourceManager.GetString("ReadLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lees meer.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoek een vereniging....
        /// </summary>
        internal static string SearchClub {
            get {
                return ResourceManager.GetString("SearchClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoek een deal....
        /// </summary>
        internal static string SearchDeal {
            get {
                return ResourceManager.GetString("SearchDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoek een job....
        /// </summary>
        internal static string SearchJob {
            get {
                return ResourceManager.GetString("SearchJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naar website.
        /// </summary>
        internal static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
    }
}
