//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rise.Client.Resources.Pages.Campus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Campus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Campus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rise.Client.Resources.Pages.Campus.Campus", typeof(Campus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over het gebouw.
        /// </summary>
        internal static string AboutBuilding {
            get {
                return ResourceManager.GetString("AboutBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over de campus.
        /// </summary>
        internal static string AboutCampus {
            get {
                return ResourceManager.GetString("AboutCampus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit gebouw heeft geen faciliteiten..
        /// </summary>
        internal static string BuildingNoFac {
            get {
                return ResourceManager.GetString("BuildingNoFac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebouwen.
        /// </summary>
        internal static string Buildings {
            get {
                return ResourceManager.GetString("Buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze campus heeft geen faciliteiten..
        /// </summary>
        internal static string CampusNoFac {
            get {
                return ResourceManager.GetString("CampusNoFac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campussen.
        /// </summary>
        internal static string Campusses {
            get {
                return ResourceManager.GetString("Campusses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaslokalen.
        /// </summary>
        internal static string Classrooms {
            get {
                return ResourceManager.GetString("Classrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faciliteiten.
        /// </summary>
        internal static string Facilities {
            get {
                return ResourceManager.GetString("Facilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdieping.
        /// </summary>
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigeer met google maps.
        /// </summary>
        internal static string GoogleMaps {
            get {
                return ResourceManager.GetString("GoogleMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laden....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekijk het weekmenu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen faciliteiten gevonden.
        /// </summary>
        internal static string NoFacilities {
            get {
                return ResourceManager.GetString("NoFacilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen resultaten gevonden.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lees minder.
        /// </summary>
        internal static string ReadLess {
            get {
                return ResourceManager.GetString("ReadLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lees meer.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoek een lokaal, gebouw,....
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een campus.
        /// </summary>
        internal static string SelectCampus {
            get {
                return ResourceManager.GetString("SelectCampus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtuele rondleiding.
        /// </summary>
        internal static string Tour {
            get {
                return ResourceManager.GetString("Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zie op plattegrond.
        /// </summary>
        internal static string ViewOnMap {
            get {
                return ResourceManager.GetString("ViewOnMap", resourceCulture);
            }
        }
    }
}
