//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rise.Client.Resources.Pages.Studentcard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StudentCard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudentCard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rise.Client.Resources.Pages.Studentcard.StudentCard", typeof(StudentCard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string BarcodeAlt {
            get {
                return ResourceManager.GetString("BarcodeAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europese studentenkaart.
        /// </summary>
        internal static string EuropeanStudentCardAlt {
            get {
                return ResourceManager.GetString("EuropeanStudentCardAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vervaldatum / Expiry date.
        /// </summary>
        internal static string ExpiryLabel {
            get {
                return ResourceManager.GetString("ExpiryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOGENT Logo.
        /// </summary>
        internal static string HogentLogoAlt {
            get {
                return ResourceManager.GetString("HogentLogoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meld je aan om je studentenkaart te bekijken..
        /// </summary>
        internal static string LoginPrompt {
            get {
                return ResourceManager.GetString("LoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentenkaart.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profielfoto.
        /// </summary>
        internal static string ProfilePhotoAlt {
            get {
                return ResourceManager.GetString("ProfilePhotoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentenkaart.
        /// </summary>
        internal static string StudentCardTitle {
            get {
                return ResourceManager.GetString("StudentCardTitle", resourceCulture);
            }
        }
    }
}
