//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rise.Client.Resources.Pages.Deadlines {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Deadline {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Deadline() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rise.Client.Resources.Pages.Deadlines.Deadline", typeof(Deadline).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle cursussen.
        /// </summary>
        internal static string AllCourses {
            get {
                return ResourceManager.GetString("AllCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltooide deadlines.
        /// </summary>
        internal static string CompletedDeadlines {
            get {
                return ResourceManager.GetString("CompletedDeadlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursus.
        /// </summary>
        internal static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadlines.
        /// </summary>
        internal static string Deadlines {
            get {
                return ResourceManager.GetString("Deadlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vervaldatum:.
        /// </summary>
        internal static string Due {
            get {
                return ResourceManager.GetString("Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in om uw deadlines te bekijken..
        /// </summary>
        internal static string LoginToViewDeadlines {
            get {
                return ResourceManager.GetString("LoginToViewDeadlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markeren als voltooid.
        /// </summary>
        internal static string MarkAsDone {
            get {
                return ResourceManager.GetString("MarkAsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen voltooide deadlines komen overeen met uw zoekopdracht..
        /// </summary>
        internal static string NoCompletedDeadlinesMatch {
            get {
                return ResourceManager.GetString("NoCompletedDeadlinesMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen aankomende deadlines.
        /// </summary>
        internal static string NoUpcomingDeadlines {
            get {
                return ResourceManager.GetString("NoUpcomingDeadlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken op titel of cursus.
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanaf:.
        /// </summary>
        internal static string Since {
            get {
                return ResourceManager.GetString("Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorteren.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op datum (oplopend).
        /// </summary>
        internal static string SortDateAsc {
            get {
                return ResourceManager.GetString("SortDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op datum (aflopend).
        /// </summary>
        internal static string SortDateDesc {
            get {
                return ResourceManager.GetString("SortDateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Aankomende deadlines.
        /// </summary>
        internal static string UpcomingDeadlinesCount {
            get {
                return ResourceManager.GetString("UpcomingDeadlinesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestand uploaden.
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
    }
}
