//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rise.Client.Resources.Pages.Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rise.Client.Resources.Pages.Settings.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aalst.
        /// </summary>
        internal static string Aalst {
            get {
                return ResourceManager.GetString("Aalst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afwezige lector.
        /// </summary>
        internal static string AbsentLecturer {
            get {
                return ResourceManager.GetString("AbsentLecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus voorkeur:.
        /// </summary>
        internal static string CampusPreference {
            get {
                return ResourceManager.GetString("CampusPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadlines.
        /// </summary>
        internal static string Deadlines {
            get {
                return ResourceManager.GetString("Deadlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gent.
        /// </summary>
        internal static string Gent {
            get {
                return ResourceManager.GetString("Gent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leswijzigingen.
        /// </summary>
        internal static string LessonChanges {
            get {
                return ResourceManager.GetString("LessonChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuws &amp; Evenementen.
        /// </summary>
        internal static string NewsAndEvents {
            get {
                return ResourceManager.GetString("NewsAndEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushmeldingen.
        /// </summary>
        internal static string PushNotifications {
            get {
                return ResourceManager.GetString("PushNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instellingen.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
