//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rise.Client.Resources.Pages.Shortcuts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shortcuts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shortcuts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rise.Client.Resources.Pages.Shortcuts.Shortcuts", typeof(Shortcuts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communicatie &amp; Software.
        /// </summary>
        internal static string CommunicatieEnSoftware {
            get {
                return ResourceManager.GetString("CommunicatieEnSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets misgegaan bij het opslaan van de volgorde..
        /// </summary>
        internal static string FoutBijOpslaanVolgorde {
            get {
                return ResourceManager.GetString("FoutBijOpslaanVolgorde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets misgegaan bij het toevoegen van de snelkoppeling..
        /// </summary>
        internal static string FoutToevoegen {
            get {
                return ResourceManager.GetString("FoutToevoegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets misgegaan bij het verwijderen van de snelkoppeling..
        /// </summary>
        internal static string FoutVerwijderen {
            get {
                return ResourceManager.GetString("FoutVerwijderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen snelkoppelingen gevonden..
        /// </summary>
        internal static string GeenSnelkoppelingen {
            get {
                return ResourceManager.GetString("GeenSnelkoppelingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen wijzigingen.
        /// </summary>
        internal static string GeenWijzigingen {
            get {
                return ResourceManager.GetString("GeenWijzigingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je moet ingelogd zijn om snelkoppelingen te bewerken..
        /// </summary>
        internal static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldingen &amp; Afwezigheid.
        /// </summary>
        internal static string MeldingenEnAfwezigheid {
            get {
                return ResourceManager.GetString("MeldingenEnAfwezigheid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn snelkoppelingen.
        /// </summary>
        internal static string MijnSnelkoppelingen {
            get {
                return ResourceManager.GetString("MijnSnelkoppelingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kunt dit item niet verder naar links verplaatsen..
        /// </summary>
        internal static string NietVerderNaarLinks {
            get {
                return ResourceManager.GetString("NietVerderNaarLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kunt dit item niet verder naar rechts verplaatsen..
        /// </summary>
        internal static string NietVerderNaarRechts {
            get {
                return ResourceManager.GetString("NietVerderNaarRechts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ondersteuning &amp; IT.
        /// </summary>
        internal static string OndersteuningEnIt {
            get {
                return ResourceManager.GetString("OndersteuningEnIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        internal static string Opslaan {
            get {
                return ResourceManager.GetString("Opslaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roosters &amp; Kalenders.
        /// </summary>
        internal static string RoostersEnKalenders {
            get {
                return ResourceManager.GetString("RoostersEnKalenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snelkoppelingen opgeslagen!.
        /// </summary>
        internal static string SnelkoppelingenOpgeslagen {
            get {
                return ResourceManager.GetString("SnelkoppelingenOpgeslagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snelkoppeling succesvol toegevoegd!.
        /// </summary>
        internal static string SnelkoppelingToegevoegd {
            get {
                return ResourceManager.GetString("SnelkoppelingToegevoegd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snelkoppeling succesvol verwijderd!.
        /// </summary>
        internal static string SnelkoppelingVerwijderd {
            get {
                return ResourceManager.GetString("SnelkoppelingVerwijderd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentenleven &amp; Welzijn.
        /// </summary>
        internal static string StudentenlevenEnWelzijn {
            get {
                return ResourceManager.GetString("StudentenlevenEnWelzijn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studiediensten.
        /// </summary>
        internal static string Studiediensten {
            get {
                return ResourceManager.GetString("Studiediensten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzigingen geannuleerd.
        /// </summary>
        internal static string WijzigingenGeannuleerd {
            get {
                return ResourceManager.GetString("WijzigingenGeannuleerd", resourceCulture);
            }
        }
    }
}
