//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rise.Client.Resources.Pages.Shortcuts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shortcuts_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shortcuts_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rise.Client.Resources.Pages.Shortcuts.Shortcuts.en", typeof(Shortcuts_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication &amp; Software.
        /// </summary>
        internal static string CommunicatieEnSoftware {
            get {
                return ResourceManager.GetString("CommunicatieEnSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving order..
        /// </summary>
        internal static string FoutBijOpslaanVolgorde {
            get {
                return ResourceManager.GetString("FoutBijOpslaanVolgorde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding shortcut..
        /// </summary>
        internal static string FoutToevoegen {
            get {
                return ResourceManager.GetString("FoutToevoegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing shortcut..
        /// </summary>
        internal static string FoutVerwijderen {
            get {
                return ResourceManager.GetString("FoutVerwijderen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shortcuts found..
        /// </summary>
        internal static string GeenSnelkoppelingen {
            get {
                return ResourceManager.GetString("GeenSnelkoppelingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes.
        /// </summary>
        internal static string GeenWijzigingen {
            get {
                return ResourceManager.GetString("GeenWijzigingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be logged in to edit your shortcuts..
        /// </summary>
        internal static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications &amp; Absence.
        /// </summary>
        internal static string MeldingenEnAfwezigheid {
            get {
                return ResourceManager.GetString("MeldingenEnAfwezigheid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My shortcuts.
        /// </summary>
        internal static string MijnSnelkoppelingen {
            get {
                return ResourceManager.GetString("MijnSnelkoppelingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can’t move this item further to the left..
        /// </summary>
        internal static string NietVerderNaarLinks {
            get {
                return ResourceManager.GetString("NietVerderNaarLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can’t move this item further to the right..
        /// </summary>
        internal static string NietVerderNaarRechts {
            get {
                return ResourceManager.GetString("NietVerderNaarRechts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support &amp; IT.
        /// </summary>
        internal static string OndersteuningEnIt {
            get {
                return ResourceManager.GetString("OndersteuningEnIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Opslaan {
            get {
                return ResourceManager.GetString("Opslaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules &amp; Calendars.
        /// </summary>
        internal static string RoostersEnKalenders {
            get {
                return ResourceManager.GetString("RoostersEnKalenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved shortcuts!.
        /// </summary>
        internal static string SnelkoppelingenOpgeslagen {
            get {
                return ResourceManager.GetString("SnelkoppelingenOpgeslagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut added successfully!.
        /// </summary>
        internal static string SnelkoppelingToegevoegd {
            get {
                return ResourceManager.GetString("SnelkoppelingToegevoegd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut removed successfully!.
        /// </summary>
        internal static string SnelkoppelingVerwijderd {
            get {
                return ResourceManager.GetString("SnelkoppelingVerwijderd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Life &amp; Wellbeing.
        /// </summary>
        internal static string StudentenlevenEnWelzijn {
            get {
                return ResourceManager.GetString("StudentenlevenEnWelzijn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Services.
        /// </summary>
        internal static string Studiediensten {
            get {
                return ResourceManager.GetString("Studiediensten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes cancelled.
        /// </summary>
        internal static string WijzigingenGeannuleerd {
            get {
                return ResourceManager.GetString("WijzigingenGeannuleerd", resourceCulture);
            }
        }
    }
}
